# This file was generated by GoReleaser. DO NOT EDIT.
class Playback < Formula
  desc ""
  homepage ""
  version "0.02-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pburakov/playback/releases/download/v0.02-beta/playback_0.02-beta_Darwin_x86_64.tar.gz"
    sha256 "91e1d415075e93346d976b5fe3068e9791ddb40d2bda516f01277393571ca363"
  elsif OS.linux?
    url "https://github.com/pburakov/playback/releases/download/v0.02-beta/playback_0.02-beta_Linux_x86_64.tar.gz"
    sha256 "f7b2d255386171ee4aae707eaac56ee9f97b77e15090ac3163e042302dfeb18e"
  end

  def install
    bin.install "playback"
  end
end
