# This file was generated by GoReleaser. DO NOT EDIT.
class Playback < Formula
  desc "CLI tool for replaying events from local file into PubSub topic in real-time."
  homepage "https://github.com/pburakov/playback/"
  version "0.05-beta"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pburakov/playback/releases/download/v0.05-beta/playback_0.05-beta_Darwin_x86_64.tar.gz"
    sha256 "50760e539eebd29c21e1e02bb93ebe53345d2663afd946950a9768b64d645f09"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pburakov/playback/releases/download/v0.05-beta/playback_0.05-beta_Linux_x86_64.tar.gz"
      sha256 "921fd500bc8309e4e832a5385ba11ecb201ee98a65ce818ce1853781973a8b8a"
    end
  end

  def install
    bin.install "playback"
  end
end
